package com.deluxedesing.app;

import android.app.Activity;
import android.content.SharedPreferences;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.text.InputType;
import android.text.TextUtils;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.widget.*;
import java.util.*;

/** Native Java implementation of the DELUXE DESIGN mobile prototype. */
public class MainActivity extends Activity {
    private final int NIGHT = Color.rgb(5, 9, 20), BLACK = Color.BLACK, SURFACE = Color.rgb(22, 27, 38);
    private final int ELEVATED = Color.rgb(34, 40, 52), FIELD = Color.rgb(41, 46, 57);
    private final int RED = Color.rgb(242, 27, 63), MAGENTA = Color.rgb(239, 0, 80), VIOLET = Color.rgb(117, 69, 184);
    private final int WHITE = Color.WHITE, MUTED = Color.rgb(154, 161, 173), SUCCESS = Color.rgb(42, 182, 115), WARNING = Color.rgb(255, 176, 32);
    private LinearLayout root, content;
    private String screen = "splash", activeTab = "Inicio", vehicle = "Porsche GT3 RS";
    private int selectedColor = RED;
    private final Deque<Integer> colorHistory = new ArrayDeque<>();
    private final Deque<Integer> redoHistory = new ArrayDeque<>();
    private boolean savedProject = false;
    private SharedPreferences prefs;
    private String userName = "Samuel Jimenez", userEmail = "samuel@deluxedesing.com";
    private final Set<String> favorites = new HashSet<>();

    @Override public void onCreate(Bundle state) {
        super.onCreate(state); prefs = getSharedPreferences("deluxe_session", MODE_PRIVATE);
        userName = prefs.getString("name", userName); userEmail = prefs.getString("email", userEmail);
        String saved = prefs.getString("favorites", ""); if (!saved.isEmpty()) favorites.addAll(Arrays.asList(saved.split("\\|")));
        showSplash();
    }

    private int dp(int n) { return (int) (n * getResources().getDisplayMetrics().density + .5f); }
    private TextView text(String value, int size, int color) {
        TextView t = new TextView(this); t.setText(value); t.setTextSize(size); t.setTextColor(color); t.setGravity(Gravity.CENTER_VERTICAL); return t;
    }
    private GradientDrawable bg(int color, float radius) { GradientDrawable g = new GradientDrawable(); g.setColor(color); g.setCornerRadius(dp((int)radius)); return g; }
    private GradientDrawable stroke(int color, int outline, float radius) { GradientDrawable g = bg(color, radius); g.setStroke(dp(1), outline); return g; }
    private GradientDrawable gradient() { GradientDrawable g = new GradientDrawable(GradientDrawable.Orientation.TL_BR, new int[]{VIOLET, MAGENTA, RED}); g.setCornerRadius(dp(12)); return g; }
    private void pad(View v, int l, int t, int r, int b) { v.setPadding(dp(l), dp(t), dp(r), dp(b)); }
    private LinearLayout column() { LinearLayout l = new LinearLayout(this); l.setOrientation(LinearLayout.VERTICAL); return l; }
    private LinearLayout row() { LinearLayout l = new LinearLayout(this); l.setOrientation(LinearLayout.HORIZONTAL); l.setGravity(Gravity.CENTER_VERTICAL); return l; }
    private void add(ViewGroup parent, View child, int w, int h) { parent.addView(child, new ViewGroup.LayoutParams(w < 0 ? w : dp(w), h < 0 ? h : dp(h))); }
    private void space(ViewGroup parent, int h) { Space s = new Space(this); add(parent, s, -1, h); }
    private void margin(View v, int l, int t, int r, int b) {
        ViewGroup.LayoutParams old = v.getLayoutParams();
        LinearLayout.LayoutParams p = old instanceof LinearLayout.LayoutParams
                ? new LinearLayout.LayoutParams((LinearLayout.LayoutParams) old)
                : new LinearLayout.LayoutParams(old.width, old.height);
        p.setMargins(dp(l), dp(t), dp(r), dp(b));
        v.setLayoutParams(p);
    }

    private void base(boolean nav) {
        root = column(); root.setBackgroundColor(NIGHT); setContentView(root);
        ScrollView scroll = new ScrollView(this); scroll.setFillViewport(true); content = column(); content.setPadding(dp(20), dp(18), dp(20), dp(18)); scroll.addView(content);
        root.addView(scroll, new LinearLayout.LayoutParams(-1, 0, 1)); if (nav) bottomNav();
    }
    private Button button(String label, boolean primary) {
        Button b = new Button(this); b.setAllCaps(false); b.setText(label); b.setTextSize(14); b.setTextColor(WHITE); b.setBackground(primary ? gradient() : stroke(SURFACE, RED, 10)); b.setMinHeight(dp(48)); return b;
    }
    private TextView chip(String label, boolean on) { TextView c = text(label, 12, on ? WHITE : MUTED); c.setGravity(Gravity.CENTER); c.setBackground(on ? bg(RED, 18) : bg(ELEVATED, 18)); pad(c, 14, 8, 14, 8); return c; }
    private void header(String title, boolean back) {
        LinearLayout h = row();
        if (back) { TextView b = text("‹", 38, WHITE); b.setGravity(Gravity.CENTER); b.setOnClickListener(v -> goBack()); add(h,b,42,48); }
        TextView titleView = text(title, 22, WHITE); titleView.setTypeface(Typeface.DEFAULT_BOLD); add(h,titleView,0,48); ((LinearLayout.LayoutParams)titleView.getLayoutParams()).weight=1;
        add(content,h,-1,52);
    }
    private EditText field(String hint, boolean password) {
        EditText e = new EditText(this); e.setHint(hint); e.setHintTextColor(MUTED); e.setTextColor(WHITE); e.setTextSize(14); e.setSingleLine(true);
        e.setInputType(password ? InputType.TYPE_CLASS_TEXT | InputType.TYPE_TEXT_VARIATION_PASSWORD : InputType.TYPE_CLASS_TEXT);
        e.setBackground(bg(FIELD, 10)); pad(e,16,0,16,0); return e;
    }
    private void addField(String hint, boolean pass) { EditText e=field(hint,pass); add(content,e,-1,52); margin(e,0,0,0,12); }
    private void logo(ViewGroup parent, int size) {
        ImageView l = new ImageView(this); l.setImageResource(R.drawable.logo_deluxe); l.setScaleType(ImageView.ScaleType.CENTER_INSIDE); l.setContentDescription("Logo DELUXE DESING"); add(parent,l,size,size);
    }
    private ImageView background(int height) { ImageView image = new ImageView(this); image.setImageResource(R.drawable.bg_porsche_gt3); image.setScaleType(ImageView.ScaleType.CENTER_CROP); image.setAlpha(.60f); image.setContentDescription("Vehículo deportivo personalizado"); add(content,image,-1,height); return image; }
    private void toast(String message) { Toast.makeText(this, message, Toast.LENGTH_SHORT).show(); }
    private void persistProfile() { prefs.edit().putString("name", userName).putString("email", userEmail).putString("favorites", TextUtils.join("|", favorites)).apply(); }
    private void bottomNav() {
        LinearLayout n = row(); n.setGravity(Gravity.CENTER); n.setBackgroundColor(BLACK); String[] tabs={"⌂\nInicio","▦\nCatálogo","▣\nProyectos","$\nCotizaciones","●\nPerfil"};
        for (String raw:tabs) { String[] p=raw.split("\\n"); TextView t=text(p[0]+"\n"+p[1],10,activeTab.equals(p[1])?RED:MUTED); t.setGravity(Gravity.CENTER); t.setLines(2); t.setBackgroundColor(BLACK); t.setOnClickListener(v->showTab(p[1])); n.addView(t,new LinearLayout.LayoutParams(0,dp(62),1)); }
        root.addView(n,new LinearLayout.LayoutParams(-1,dp(62)));
    }

    private void showSplash() {
        screen="splash"; base(false); background(275); Space top=new Space(this); add(content,top,-1,12); logo(content,122); space(content,20);
        TextView hero=text("TU VEHÍCULO\nTU ESTILO\nSIN LÍMITES",28,WHITE); hero.setTypeface(Typeface.DEFAULT_BOLD); add(content,hero,-1,128); space(content,10);
        TextView sub=text("Personaliza. Visualiza. Hazlo realidad.",14,MUTED); add(content,sub,-1,34); space(content,35);
        Button start=button("COMIENZA A SOÑAR  →",true); start.setOnClickListener(v->showLogin()); add(content,start,-1,54);
    }
    private void showLogin() {
        screen="login"; base(false); background(180); header("",true); LinearLayout center=column(); center.setGravity(Gravity.CENTER_HORIZONTAL); logo(center,100); space(center,20);
        TextView welcome=text("BIENVENIDO A\nDELUXE DESING",25,WHITE); welcome.setTypeface(Typeface.DEFAULT_BOLD); welcome.setGravity(Gravity.CENTER); add(center,welcome,-1,70); space(center,22); content.addView(center);
        EditText email=field("Correo electrónico",false); add(content,email,-1,52); margin(email,0,0,0,12); EditText password=field("Contraseña",true); add(content,password,-1,52); margin(password,0,0,0,12); TextView recover=text("¿Olvidaste tu contraseña?",13,RED); recover.setGravity(Gravity.RIGHT); recover.setOnClickListener(v->showRecover()); add(content,recover,-1,36);
        Button enter=button("Ingresar",true); enter.setOnClickListener(v->{ if (!TextUtils.isEmpty(email.getText())) { userEmail=email.getText().toString().trim(); } persistProfile(); showHome(); }); add(content,enter,-1,52); space(content,12); TextView register=text("¿Aún no tienes cuenta?  Regístrate",14,WHITE); register.setGravity(Gravity.CENTER); register.setOnClickListener(v->showRegister()); add(content,register,-1,42);
    }
    private void showRegister() { screen="register"; base(false); background(150); header("REGÍSTRATE",true); TextView s=text("Crea tu cuenta y comienza a diseñar.",14,MUTED); add(content,s,-1,36); EditText name=field("Nombre completo",false);add(content,name,-1,52);margin(name,0,0,0,12);EditText email=field("Correo electrónico",false);add(content,email,-1,52);margin(email,0,0,0,12);addField("Teléfono",false);EditText pass=field("Contraseña",true);add(content,pass,-1,52);margin(pass,0,0,0,12);EditText confirm=field("Confirmar contraseña",true);add(content,confirm,-1,52);margin(confirm,0,0,0,12);Button b=button("Crear cuenta",true); b.setOnClickListener(v->{if(TextUtils.isEmpty(name.getText())||TextUtils.isEmpty(email.getText())||pass.length()<6){toast("Completa los datos y usa una contraseña de 6 caracteres");return;}if(!pass.getText().toString().equals(confirm.getText().toString())){toast("Las contraseñas no coinciden");return;}userName=name.getText().toString().trim();userEmail=email.getText().toString().trim();persistProfile();toast("Cuenta creada correctamente");showHome();}); add(content,b,-1,52); }
    private void showRecover() { screen="recover"; base(false); background(160); header("RECUPERAR CONTRASEÑA",true); TextView d=text("Te enviaremos un enlace seguro a tu correo registrado.",14,MUTED); add(content,d,-1,55); EditText email=field("Correo electrónico",false);add(content,email,-1,52);margin(email,0,0,0,12);Button b=button("Confirmar email",true); b.setOnClickListener(v->{if(TextUtils.isEmpty(email.getText())){toast("Ingresa tu correo");return;}userEmail=email.getText().toString().trim();toast("Enlace de recuperación enviado");showPasswordUpdate();}); add(content,b,-1,52); }
    private void showPasswordUpdate() { screen="update"; base(false); header("ACTUALIZAR CONTRASEÑA",true); EditText pass=field("Nueva contraseña",true);add(content,pass,-1,52);margin(pass,0,0,0,12);EditText confirm=field("Repite tu contraseña",true);add(content,confirm,-1,52);margin(confirm,0,0,0,12);Button b=button("Guardar cambios",true); b.setOnClickListener(v->{if(pass.length()<6||!pass.getText().toString().equals(confirm.getText().toString())){toast("Verifica la contraseña");return;}toast("Contraseña actualizada");showLogin();}); add(content,b,-1,52); }

    private void showHome() {
        screen="home"; activeTab="Inicio"; base(true); LinearLayout h=row(); logo(h,48); TextView hello=text("  Bienvenido,\n  "+userName,15,WHITE); add(h,hello,0,50); ((LinearLayout.LayoutParams)hello.getLayoutParams()).weight=1; TextView bell=text("◉",24,WHITE); bell.setOnClickListener(v->showNotifications()); add(h,bell,42,50); add(content,h,-1,56);
        TextView motto=text("IDEAS QUE\nCOBRAN VIDA",26,WHITE); motto.setTypeface(Typeface.DEFAULT_BOLD); add(content,motto,-1,80); TextView caption=text("Haz que tu vehículo refleje tu estilo.",14,MUTED); add(content,caption,-1,38);
        LinearLayout quick=row(); quick.setGravity(Gravity.CENTER); String[] items={"＋\nNuevo\nproyecto","▣\nMis\nvehículos","✦\nMis\ndiseños","⌖\nSucursales"}; for(String x:items){TextView q=text(x,12,WHITE);q.setGravity(Gravity.CENTER);q.setLines(3);q.setBackground(bg(ELEVATED,12)); final String z=x; q.setOnClickListener(v->{if(z.contains("Nuevo"))showCatalog();else if(z.contains("Sucursales"))showBranches();else showVehicles();}); quick.addView(q,new LinearLayout.LayoutParams(0,dp(84),1)); margin(q,3,0,3,0);} add(content,quick,-1,88); space(content,20); sectionTitle("Proyectos recientes", "Ver todos", v->showProjects()); projectCard("BMW M4 Competition","En proceso · 65%",65,SUCCESS); projectCard("Porsche GT3 RS - Urban Dark","Borrador",20,WARNING);
    }
    private void sectionTitle(String title,String action,View.OnClickListener listener){LinearLayout r=row();TextView a=text(title,18,WHITE);a.setTypeface(Typeface.DEFAULT_BOLD);add(r,a,0,38);((LinearLayout.LayoutParams)a.getLayoutParams()).weight=1;TextView b=text(action,13,RED);b.setGravity(Gravity.RIGHT);b.setOnClickListener(listener);add(r,b,90,38);add(content,r,-1,42);}
    private void projectCard(String name,String status,int percent,int tint){LinearLayout c=column();c.setBackground(bg(SURFACE,14));pad(c,14,12,14,12);TextView n=text(name,16,WHITE);n.setTypeface(Typeface.DEFAULT_BOLD);add(c,n,-1,28);TextView s=text(status+" · Entrega estimada: 25 Jun",12,MUTED);add(c,s,-1,26);ProgressBar p=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);p.setProgress(percent);p.setProgressTintList(android.content.res.ColorStateList.valueOf(tint));add(c,p,-1,8);c.setOnClickListener(v->showProjectDetail());add(content,c,-1,96);margin(c,0,0,0,12);}

    private void showCatalog(){screen="catalog";activeTab="Catálogo";base(true);header("Catálogo",false);EditText search=field("Buscar por marca, modelo o año",false);add(content,search,-1,50);space(content,12);LinearLayout filters=row();String[] f={"Todos","Deportivos","SUV","Sedán","PickUp"};for(String x:f){TextView c=chip(x,x.equals("Todos"));filters.addView(c);margin(c,0,0,7,0);}add(content,filters,-1,42);space(content,14);vehicleCard("Porsche GT3 RS","Deportivo · 2024",RED);vehicleCard("BMW M4 Competition","Deportivo · 2024",Color.rgb(35,115,230));vehicleCard("Ford Mustang GT","Muscle car · 2024",Color.rgb(225,55,38));vehicleCard("Audi R8","Deportivo · 2023",Color.rgb(45,175,190));}
    private void vehicleCard(String name,String detail,int color){LinearLayout c=row();c.setBackground(bg(SURFACE,14));pad(c,12,10,12,10);VehicleView car=new VehicleView(this,color);add(c,car,112,70);LinearLayout info=column();TextView n=text(name,15,WHITE);n.setTypeface(Typeface.DEFAULT_BOLD);add(info,n,-1,25);add(info,text(detail,12,MUTED),-1,22);TextView more=text("Ver detalles  →",12,RED);more.setOnClickListener(v->{vehicle=name;showVehicleDetail();});add(info,more,-1,22);add(c,info,0,70);((LinearLayout.LayoutParams)info.getLayoutParams()).weight=1;add(content,c,-1,92);margin(c,0,0,0,12);}
    private void showVehicleDetail(){screen="detail";activeTab="Catálogo";base(true);header(vehicle,true);TextView cat=text("Deportivo · "+(favorites.contains(vehicle)?"♥ En favoritos":"♡ Añadir a favoritos"),13,RED);cat.setOnClickListener(v->{if(favorites.contains(vehicle)){favorites.remove(vehicle);toast("Eliminado de favoritos");}else{favorites.add(vehicle);toast("Añadido a favoritos");}persistProfile();showVehicleDetail();});add(content,cat,-1,28);VehicleView car=new VehicleView(this,selectedColor);car.setBackground(bg(BLACK,16));add(content,car,-1,205);space(content,10);LinearLayout thumbs=row();for(String a:new String[]{"Frontal","Lateral","Trasera"}){TextView t=text(a,11,MUTED);t.setGravity(Gravity.CENTER);t.setBackground(bg(ELEVATED,9));thumbs.addView(t,new LinearLayout.LayoutParams(0,dp(34),1));margin(t,3,0,3,0);}add(content,thumbs,-1,38);space(content,15);sectionTitle("Especificaciones","",null);spec("Motor","4.0L 6 cilindros bóxer");spec("Potencia","525 HP");spec("Transmisión","PDK 7 velocidades");spec("Tracción","Trasera");Button b=button("PERSONALIZAR",true);b.setOnClickListener(v->showEditor());add(content,b,-1,54);}
    private void spec(String k,String v){LinearLayout r=row();TextView a=text(k,13,MUTED);TextView b=text(v,13,WHITE);b.setGravity(Gravity.RIGHT);add(r,a,0,30);((LinearLayout.LayoutParams)a.getLayoutParams()).weight=1;add(r,b,0,30);((LinearLayout.LayoutParams)b.getLayoutParams()).weight=1;add(content,r,-1,30);}

    @android.annotation.SuppressLint("ResourceType")
    private void showEditor(){screen="editor";activeTab="Catálogo";base(true);header("PERSONALIZAR",true);Button save=button("Guardar",false);save.setOnClickListener(v->showConfirm());add(content,save,-1,46);VehicleView car=new VehicleView(this,selectedColor);car.setId(909);car.setBackground(bg(BLACK,14));add(content,car,-1,210);space(content,10);LinearLayout actions=row();TextView undo=chip("↶ Deshacer",false);undo.setOnClickListener(v->{if(!colorHistory.isEmpty()){redoHistory.push(selectedColor);selectedColor=colorHistory.pop();refreshEditorCar();}});TextView redo=chip("↷ Rehacer",false);redo.setOnClickListener(v->{if(!redoHistory.isEmpty()){colorHistory.push(selectedColor);selectedColor=redoHistory.pop();refreshEditorCar();}});actions.addView(undo);actions.addView(redo);margin(redo,10,0,0,0);add(content,actions,-1,42);space(content,12);TextView label=text("Color del vehículo",17,WHITE);label.setTypeface(Typeface.DEFAULT_BOLD);add(content,label,-1,32);LinearLayout colors=row();int[] cs={RED,Color.WHITE,Color.rgb(22,37,75),Color.rgb(35,175,220),Color.rgb(255,174,0),Color.rgb(20,20,20)};for(int c:cs){TextView dot=text("",1,WHITE);dot.setBackground(stroke(c,c==selectedColor?WHITE:c,20));final int newColor=c;dot.setOnClickListener(v->{colorHistory.push(selectedColor);redoHistory.clear();selectedColor=newColor;refreshEditorCar();});colors.addView(dot,new LinearLayout.LayoutParams(dp(34),dp(34)));margin(dot,0,0,10,0);}add(content,colors,-1,38);space(content,12);LinearLayout finish=row();for(String x:new String[]{"Sólido","Mate","Metálico","Perlado"}){TextView z=chip(x,x.equals("Metálico"));finish.addView(z);margin(z,0,0,7,0);}add(content,finish,-1,42);space(content,14);TextView cats=text("Pintura     Vinilos     Llantas\nBody kit    Faros       Accesorios\nInteriores",14,WHITE);cats.setLines(3);cats.setGravity(Gravity.CENTER);cats.setBackground(bg(ELEVATED,12));pad(cats,8,14,8,14);add(content,cats,-1,80);}
    @android.annotation.SuppressLint("ResourceType")
    private void refreshEditorCar(){VehicleView v=findViewById(909);if(v!=null){v.color=selectedColor;v.invalidate();}}
    private void showConfirm(){screen="confirm";activeTab="Catálogo";base(true);header("Confirmar cambios",true);VehicleView car=new VehicleView(this,selectedColor);car.setBackground(bg(BLACK,14));add(content,car,-1,210);space(content,14);String[][] changes={{"Pintura","Color personalizado"},{"Acabado","Metálico"},{"Vinilos","Racing lateral"},{"Llantas","Sport forged"},{"Body kit","Urban Dark"},{"Faros","LED smoked"},{"Accesorios","Alerón carbono"},{"Interiores","Alcantara negra"}};for(String[] x:changes)spec(x[0],x[1]);Button b=button("Confirmar cambios",true);b.setOnClickListener(v->showReady());add(content,b,-1,54);}
    private void showReady(){screen="ready";activeTab="Proyectos";savedProject=true;base(true);TextView ok=text("✓",54,SUCCESS);ok.setGravity(Gravity.CENTER);add(content,ok,-1,65);TextView h=text("¡PROYECTO LISTO!",24,WHITE);h.setTypeface(Typeface.DEFAULT_BOLD);h.setGravity(Gravity.CENTER);add(content,h,-1,42);TextView name=text(vehicle+" - Red Black Racing",15,MUTED);name.setGravity(Gravity.CENTER);add(content,name,-1,32);VehicleView car=new VehicleView(this,selectedColor);car.setBackground(bg(BLACK,14));add(content,car,-1,190);space(content,18);Button p=button("Guardar en mis proyectos",true);p.setOnClickListener(v->showProjects());add(content,p,-1,50);space(content,10);Button quote=button("Generar cotización",false);quote.setOnClickListener(v->showNewQuote());add(content,quote,-1,50);TextView other=text("Exportar imágenes     Compartir",13,RED);other.setGravity(Gravity.CENTER);add(content,other,-1,42);}

    private void showProjects(){screen="projects";activeTab="Proyectos";base(true);header("Proyectos",false);TextView m=text("IDEAS QUE COBRAN VIDA",18,WHITE);m.setTypeface(Typeface.DEFAULT_BOLD);add(content,m,-1,35);LinearLayout tabs=row();for(String x:new String[]{"Activos","Entregados","Borradores"}){TextView t=chip(x,x.equals("Activos"));tabs.addView(t);margin(t,0,0,8,0);}add(content,tabs,-1,42);space(content,14);projectCard("BMW M4 Competition","En proceso · 65%",65,SUCCESS);projectCard("Toyota Tacoma","Casi listo · 85%",85,WARNING);projectCard("Audi R8","Completado",100,SUCCESS);if(savedProject)projectCard(vehicle+" - Red Black Racing","Borrador",20,WARNING);}
    private void showProjectDetail(){screen="projectdetail";activeTab="Proyectos";base(true);header("Proyecto detalle",true);VehicleView car=new VehicleView(this,selectedColor);car.setBackground(bg(BLACK,14));add(content,car,-1,190);TextView state=text("EN PROCESO  ·  65%",13,SUCCESS);state.setGravity(Gravity.CENTER);add(content,state,-1,34);TextView n=text("Porsche GT3 RS - Urban Dark",18,WHITE);n.setTypeface(Typeface.DEFAULT_BOLD);add(content,n,-1,34);spec("Fecha de creación","12 de junio de 2026");spec("Cambios","Pintura, vinilos y llantas");Button edit=button("Editar proyecto",false);edit.setOnClickListener(v->showEditor());add(content,edit,-1,48);space(content,9);Button q=button("Generar cotización",true);q.setOnClickListener(v->showNewQuote());add(content,q,-1,48);}

    private void showQuotes(){screen="quotes";activeTab="Cotizaciones";base(true);header("Cotizaciones",false);LinearLayout summary=row();metric(summary,"03","Pendientes",WARNING);metric(summary,"08","Aprobadas",SUCCESS);add(content,summary,-1,84);Button b=button("＋ Nueva cotización",true);b.setOnClickListener(v->showNewQuote());add(content,b,-1,48);space(content,14);quoteCard("Porsche GT3 RS","Pintura completa","$ 4,850","En revisión",WARNING);quoteCard("BMW M4 Competition","Body kit sport","$ 3,200","Aprobada",SUCCESS);quoteCard("Toyota Tacoma","Vinilado lateral","$ 1,150","Pendiente",WARNING);}
    private void metric(LinearLayout parent,String number,String label,int tint){LinearLayout c=column();c.setGravity(Gravity.CENTER);c.setBackground(bg(SURFACE,12));TextView n=text(number,24,tint);n.setTypeface(Typeface.DEFAULT_BOLD);n.setGravity(Gravity.CENTER);add(c,n,-1,35);TextView l=text(label,12,MUTED);l.setGravity(Gravity.CENTER);add(c,l,-1,22);parent.addView(c,new LinearLayout.LayoutParams(0,dp(70),1));margin(c,4,0,4,0);}
    private void quoteCard(String car,String service,String price,String status,int tint){LinearLayout c=column();c.setBackground(bg(SURFACE,12));pad(c,14,10,14,10);TextView n=text(car,15,WHITE);n.setTypeface(Typeface.DEFAULT_BOLD);add(c,n,-1,25);TextView line=text(service+"     "+price,13,MUTED);add(c,line,-1,24);TextView s=text(status,12,tint);add(c,s,-1,21);c.setOnClickListener(v->showQuoteDetail());add(content,c,-1,82);margin(c,0,0,0,11);}
    private void showNewQuote(){screen="newquote";activeTab="Cotizaciones";base(true);header("Nueva cotización",true);addField("Proyecto asociado",false);addField("Nombre del cliente",false);addField("Notas y detalles especiales",false);TextView sum=text("Resumen estimado\nKit de personalización · $ 3,600\nGarantía · 12 meses",14,WHITE);sum.setBackground(bg(SURFACE,12));pad(sum,14,14,14,14);add(content,sum,-1,90);space(content,14);Button b=button("Generar cotización",true);b.setOnClickListener(v->showQuoteDetail());add(content,b,-1,50);}
    private void showQuoteDetail(){screen="quotedetail";activeTab="Cotizaciones";base(true);header("Cotización",true);TextView id=text("COT-2026-001  ·  En revisión",13,WARNING);add(content,id,-1,30);TextView car=text("Porsche GT3 RS - Urban Dark",18,WHITE);car.setTypeface(Typeface.DEFAULT_BOLD);add(content,car,-1,35);quoteLine("Pintura completa","$ 2,000");quoteLine("Vinilado lateral","$ 650");quoteLine("Llantas deportivas","$ 1,800");quoteLine("Mano de obra certificada","$ 400");TextView total=text("TOTAL ESTIMADO     $ 4,850",18,RED);total.setTypeface(Typeface.DEFAULT_BOLD);total.setGravity(Gravity.CENTER_VERTICAL);total.setBackground(bg(SURFACE,12));pad(total,14,0,14,0);add(content,total,-1,58);space(content,14);Button share=button("Compartir cotización",false);share.setOnClickListener(v->toast("Cotización preparada para compartir"));add(content,share,-1,48);space(content,9);Button pdf=button("Descargar PDF",true);pdf.setOnClickListener(v->toast("PDF generado y listo para descargar"));add(content,pdf,-1,48);}
    private void quoteLine(String item,String price){LinearLayout r=row();TextView a=text(item,14,MUTED);TextView b=text(price,14,WHITE);b.setGravity(Gravity.RIGHT);add(r,a,0,42);((LinearLayout.LayoutParams)a.getLayoutParams()).weight=1;add(r,b,110,42);add(content,r,-1,42);}

    private void showProfile(){screen="profile";activeTab="Perfil";base(true);header("Perfil",false);LinearLayout top=row();logo(top,80);TextView n=text("  "+userName+"\n  "+userEmail,15,WHITE);add(top,n,0,70);((LinearLayout.LayoutParams)n.getLayoutParams()).weight=1;add(content,top,-1,88);LinearLayout stats=row();metric(stats,"03","Mis vehículos",RED);metric(stats,"08","Cotizaciones",RED);metric(stats,"05","Proyectos",RED);add(content,stats,-1,84);space(content,16);for(String x:new String[]{"Editar perfil","Mis vehículos","Mis cotizaciones","Mis proyectos","Favoritos","Notificaciones"}){TextView line=text(x+"                                      ›",15,WHITE);line.setBackground(bg(SURFACE,10));pad(line,14,0,12,0);if(x.equals("Editar perfil"))line.setOnClickListener(v->showEditProfile());if(x.equals("Mis vehículos"))line.setOnClickListener(v->showVehicles());if(x.equals("Mis cotizaciones"))line.setOnClickListener(v->showQuotes());if(x.equals("Mis proyectos"))line.setOnClickListener(v->showProjects());if(x.equals("Favoritos"))line.setOnClickListener(v->showFavorites());if(x.equals("Notificaciones"))line.setOnClickListener(v->showNotifications());add(content,line,-1,48);margin(line,0,0,0,8);}TextView help=text("SOPORTE\n+591 700 00000 · hola@deluxedesing.com\nLun–Vie 09:00–18:00",13,MUTED);help.setBackground(bg(SURFACE,10));pad(help,14,12,14,12);add(content,help,-1,78);space(content,10);Button logout=button("Cerrar sesión",false);logout.setOnClickListener(v->{prefs.edit().clear().apply();favorites.clear();toast("Sesión cerrada");showLogin();});add(content,logout,-1,48);}
    private void showEditProfile(){screen="editprofile";activeTab="Perfil";base(true);header("Editar perfil",true);EditText name=field("Nombre completo",false);name.setText(userName);add(content,name,-1,52);margin(name,0,0,0,12);EditText email=field("Correo electrónico",false);email.setText(userEmail);add(content,email,-1,52);margin(email,0,0,0,12);addField("Teléfono",false);Button b=button("Guardar perfil",true);b.setOnClickListener(v->{if(TextUtils.isEmpty(name.getText())||TextUtils.isEmpty(email.getText())){toast("Completa nombre y correo");return;}userName=name.getText().toString().trim();userEmail=email.getText().toString().trim();persistProfile();toast("Perfil actualizado");showProfile();});add(content,b,-1,50);}
    private void showFavorites(){screen="favorites";activeTab="Perfil";base(true);header("Favoritos",true);if(favorites.isEmpty()){TextView empty=text("Aún no guardaste vehículos favoritos.\nExplora el catálogo para añadirlos.",15,MUTED);empty.setGravity(Gravity.CENTER);add(content,empty,-1,130);Button b=button("Ir al catálogo",true);b.setOnClickListener(v->showCatalog());add(content,b,-1,48);}else{for(String item:favorites)vehicleCard(item,"Guardado en favoritos",RED);}}
    private void showVehicles(){screen="vehicles";activeTab="Perfil";base(true);header("Mis vehículos",true);vehicleCard("Porsche GT3 RS","Deportivo · Favorito",RED);vehicleCard("BMW M4 Competition","Deportivo",Color.rgb(35,115,230));vehicleCard("Mustang GT 2024","Muscle car",Color.rgb(225,55,38));Button b=button("Ver catálogo",true);b.setOnClickListener(v->showCatalog());add(content,b,-1,48);}
    private void showBranches(){screen="branches";activeTab="Inicio";base(true);header("Sucursales",true);TextView map=text("⌖\nMAPA DE SUCURSALES",18,RED);map.setGravity(Gravity.CENTER);map.setBackground(bg(SURFACE,14));add(content,map,-1,160);space(content,14);branch("Deluxe Central - La Paz","Av. Arce 2150 · +591 700 00000");branch("Deluxe San Miguel","C. 21 de Calacoto · +591 700 00001");branch("Deluxe Santa Cruz","Av. San Martín · +591 700 00002");}
    private void branch(String name,String detail){TextView b=text(name+"\n"+detail+"\nLun–Vie 09:00–18:00 · Ver en mapa",14,WHITE);b.setLines(3);b.setBackground(bg(SURFACE,12));pad(b,14,8,14,8);add(content,b,-1,82);margin(b,0,0,0,10);}
    private void showNotifications(){screen="notifications";activeTab="Perfil";base(true);header("Notificaciones",true);notice("Proyecto completado","Tu Audi R8 está listo para entrega.","Ahora",SUCCESS);notice("Cotización aprobada","La cotización COT-2026-001 fue aprobada.","Hace 2 h",RED);notice("Nuevo modelo disponible","El Porsche GT3 RS 2025 ya está en catálogo.","Ayer",VIOLET);}
    private void notice(String title,String detail,String time,int tint){LinearLayout c=column();c.setBackground(bg(SURFACE,12));pad(c,14,10,14,10);TextView h=text("●  "+title,15,tint);h.setTypeface(Typeface.DEFAULT_BOLD);add(c,h,-1,25);add(c,text(detail,13,WHITE),-1,23);add(c,text(time,12,MUTED),-1,18);add(content,c,-1,82);margin(c,0,0,0,10);}

    private void showTab(String tab){if(tab.equals("Inicio"))showHome();else if(tab.equals("Catálogo"))showCatalog();else if(tab.equals("Proyectos"))showProjects();else if(tab.equals("Cotizaciones"))showQuotes();else showProfile();}
    private void goBack(){if(screen.equals("login"))showSplash();else if(screen.equals("register")||screen.equals("recover"))showLogin();else if(screen.equals("update"))showRecover();else if(screen.equals("detail"))showCatalog();else if(screen.equals("editor"))showVehicleDetail();else if(screen.equals("confirm"))showEditor();else if(screen.equals("ready"))showHome();else if(screen.equals("projectdetail"))showProjects();else if(screen.equals("newquote")||screen.equals("quotedetail"))showQuotes();else if(screen.equals("vehicles")||screen.equals("notifications")||screen.equals("editprofile")||screen.equals("favorites"))showProfile();else if(screen.equals("branches"))showHome();else showHome();}
    @Override public void onBackPressed(){goBack();}

    /** Draws a responsive sports-car preview so the editor works without external image dependencies. */
    public static class VehicleView extends View {
        int color; Paint p=new Paint(Paint.ANTI_ALIAS_FLAG); public VehicleView(android.content.Context c,int color){super(c);this.color=color;}
        @Override protected void onDraw(Canvas c){super.onDraw(c);float w=getWidth(),h=getHeight();p.setColor(Color.rgb(7,11,20));c.drawRect(0,0,w,h,p);p.setColor(Color.argb(45,255,20,55));c.drawCircle(w*.76f,h*.25f,w*.42f,p);p.setColor(color);Path body=new Path();body.moveTo(w*.12f,h*.65f);body.lineTo(w*.25f,h*.43f);body.lineTo(w*.58f,h*.34f);body.lineTo(w*.82f,h*.47f);body.lineTo(w*.91f,h*.65f);body.lineTo(w*.86f,h*.75f);body.lineTo(w*.17f,h*.75f);body.close();c.drawPath(body,p);p.setColor(Color.rgb(12,16,24));Path glass=new Path();glass.moveTo(w*.32f,h*.45f);glass.lineTo(w*.59f,h*.38f);glass.lineTo(w*.73f,h*.49f);glass.lineTo(w*.29f,h*.56f);glass.close();c.drawPath(glass,p);p.setColor(Color.BLACK);c.drawCircle(w*.28f,h*.74f,h*.13f,p);c.drawCircle(w*.76f,h*.74f,h*.13f,p);p.setColor(Color.DKGRAY);c.drawCircle(w*.28f,h*.74f,h*.075f,p);c.drawCircle(w*.76f,h*.74f,h*.075f,p);p.setColor(Color.WHITE);c.drawRect(w*.78f,h*.56f,w*.88f,h*.59f,p);p.setColor(Color.argb(210,255,255,255));c.drawLine(w*.15f,h*.68f,w*.88f,h*.68f,p);}
    }
}
